FROM golang:1.25.4-alpine AS builder

WORKDIR /build

COPY api/openapi/workstream-gateway.yaml ./workstream-gateway.yaml

COPY go.mod go.sum ./
RUN go mod download

COPY . .

ENV CGO_ENABLED=0 GOOS=linux GOARCH=amd64
RUN go build -ldflags="-s -w" -o workstream-gateway ./cmd/workstream-gateway

FROM scratch

COPY --from=builder /build/workstream-gateway /workstream-gateway
COPY --from=builder /build/workstream-gateway.yaml /workstream-gateway.yaml

ENTRYPOINT ["/workstream-gateway"]
