FROM golang:1.25.4-alpine AS builder

WORKDIR /build

COPY go.mod go.sum ./
RUN go mod download

COPY . .

ENV CGO_ENABLED=0 GOOS=linux GOARCH=amd64
RUN go build -ldflags="-s -w" -o workstream-tasks ./cmd/workstream-tasks

FROM scratch

COPY --from=builder ["/build/workstream-tasks", "/"]

ENTRYPOINT ["/workstream-tasks"]
