openapi: 3.2.0

info:
  title: Tasks microservice
  description: |
    API for creating, reading, and completing tasks.
  version: 1.0.0

servers:
  - url: http://localhost:8080/api/v1
    description: Local development server.

paths:
  /tasks:
    get:
      operationId: getTasks
      summary: List existing tasks
      tags: [tasks]
      responses:
        "200":
          description: A list of tasks
    post:
      operationId: createTask
      summary: Creates a task
      tags: [tasks]
      requestBody:
        required: true
        content:
          application/json: {}
      responses:
        "201":
          description: Task successfully created

  /tasks/{id}/complete:
    post:
      operationId: completeTask
      summary: Completes a task
      tags: [tasks]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Task successfully completed

components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: string
          format: uuid
